version: "3.3"
services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    environment:
      MYSQL_DATABASE: my-docker-project
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - db
  php-fpm:
    image: webdevops/php-dev:7.3
    hostname: php-fpm
    volumes:
      - "./:/app"
    working_dir: "/app"
    depends_on:
      - mysql
    networks:
      - db
  nginx:
    image: webdevops/nginx
    hostname: nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php-fpm:9000
    ports:
      - "80:80"
    volumes:
       - "./:/app"
    depends_on:
      - php-fpm
    networks:
      - db

networks:
  db:
