<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFPXzlb9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFPXzlb9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFPXzlb9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFPXzlb9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFPXzlb9\App_KernelDevDebugContainer([
    'container.build_hash' => 'FPXzlb9',
    'container.build_id' => 'a8ed7fcd',
    'container.build_time' => 1582545999,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFPXzlb9');
